---
- hosts: localhost
  connection: local
  
  gather_facts: true
  
  tasks:
    - debug: var=ansible_facts
      
 #   - debug: var=ansible_all_ipv4_addresses
 #   - debug: var=ansible_default_ipv4.address
